---
apiVersion: k8s.io/v1
kind: Function
metadata:
  name: function
spec:
  handler: hello.handler
  runtime: perl5.26
  function: |
      use strict;
      sub handler {
         return "hello world"
      }

      1
