apiVersion: k8s.io/v1
kind: Function
metadata:
  name: {{ template  "fullname" . }}
spec:
  handler: minio-ocr.handler
  runtime: python2.7
  type: HTTP
  deps: |
    minio
    tika
    pymongo
    kubernetes
  function: |
      # -*- coding: UTF-8 -*-
      import base64
      import tempfile
      import json
      import tika
      import pymongo
      tika.TikaClientOnly = True
      from tika import parser
      from pymongo import MongoClient
      from kubernetes import client, config
      from minio import Minio
      from minio.error import ResponseError
      
      config.load_incluster_config()
      
      v1=client.CoreV1Api()
      
      for secrets in v1.list_secret_for_all_namespaces().items:
          if secrets.metadata.name == 'ocr-minio-user':
              access_key =  base64.b64decode(secrets.data['accesskey'])
              secret_key =  base64.b64decode(secrets.data['secretkey'])

      mongo = MongoClient('ocr-mongodb', 27017)

      client = Minio('ocr-minio-svc:9000', 
                        access_key=access_key,
                        secret_key=secret_key, 
                        secure=False)

      print 'Loading function...'
      
      def handler(context):
        data = context.json
        if data['EventType'] == "s3:ObjectCreated:Put" : 
      
              tf = tempfile.NamedTemporaryFile(delete=False)
              bucket = data['Key'].split('/')[0]
              filename = data['Key'].split('/')[1]
      
              try:
                  print 'Fetching file'
                  client.fget_object(bucket, filename, tf.name)
              except ResponseError as err:
                  print 'Error fetching file'
                  print err


              print 'Sending file to Tika'
              parsed = parser.from_file(tf.name, serverEndpoint='http://ocr-tika-server:80/tika')
              ocrdata = json.dumps(parsed, ensure_ascii=True)

              db = mongo['ocr']
              result = db.processed.insert_one(parsed)
              print 'Document Saved!'
              print('Document proccessed: {0}'.format(result.inserted_id))


      
              # puts the same file in a done OCR bucket
              #        ocr_name = '/tmp/' +  filename + '.ocr'
              #        file = open(ocr_name,'w')
              #        file.write(parsed)
              #        file.close()
      
              #        try:
              #            client.fput_object('done',ocr_name,tf.name)
              #        except ResponseError as err:
              #            print err
      
        else:
              print "Minio file deletion event"
      
        return "OCR Finished"
