dependencies:
- name: tika-server
  version: 0.1.x
  repository: http://127.0.0.1:8879

- name: mongodb
  version: 0.4.x
  repository: https://kubernetes-charts.storage.googleapis.com/

- name: minio
  version: 0.1.x
  repository: https://kubernetes-charts.storage.googleapis.com/

