minio:
  image: minio/minio
  imageTag: RELEASE.2017-03-16T21-50-32Z
  imagePullPolicy: IfNotPresent
  mode: standalone
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  configPath: ""
  mountPath: "/export"
  replicas: 4
  persistence:
    enabled: false
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass: <storageClass>
    accessMode: ReadWriteOnce
    size: 10Gi
  serviceType: NodePort
  servicePort: 9000
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
  minioConfig:
    aqmp:
      enable: false
      url: ""
      exchange: ""
      routingKey: ""
      exchangeType: ""
      mandatory: false
      immediate: false
      durable: false
      internal: false
      noWait: false
      autoDeleted: false
    nats:
      enable: false
      address: ""
      subject: ""
      username: ""
      password: ""
      token: ""
      secure: false
      pingInterval: 0
      enableStreaming: false
      clusterID: ""
      clientID: ""
      async: false
      maxPubAcksInflight: 0
    elasticsearch:
      enable: false
      url: ""
      index: ""
    redis:
      enable: false
      address: ""
      password: ""
      key: ""
    postgresql:
      enable: false
      connectionString: ""
      table: ""
      host: ""
      port: ""
      user: ""
      password: ""
      database: ""
    kafka:
      enable: false
      brokers: "null"
      topic: ""
    webhook:
      enable: true 
      endpoint: "http://ocr-ocr-pipeline:8080"

mongodb:  
  image: bitnami/mongodb:3.4.3-r0
  mongodbRootPassword:
  mongodbUsername:
  mongodbPassword:
  mongodbDatabase:
  persistence:
    enabled: false
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 8Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
   
tika-server:
  image:
    repository: bitnami/tika-server
    tag: 1.14
    pullPolicy: IfNotPresent
  tika:
    version: 1.14
    translator: 
      google:
        clientsecret: PUT_YOUR_KEY_HERE
  service:
    name: tika
    type: ClusterIP
    externalPort: 80
    internalPort: 9998
  resources:
    limits:
      cpu: 100m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 1024Mi


